DEBUG = -v --fargs "-Ofast -DFORTHON -cpp -g" #--fargs "-C=array" #--fargs "-CB -traceback"

SO = so
PUBLICHOME = 
LARGS =
BUILDDIR = build
DIRLIST = com aph bbb api flx grd svr wdf ppp ncl
MYPYTHON ?= python3
FORTHON = Forthon3
PYTAG ?= default
BUILDBASE = -v --build-base $(BUILDDIR)
INSTALLARGS = --pkgbase uedge $(BUILDBASE) $(OMPFLAGS) $(LARGS)

# If building with --omp, ensure the OpenMP runtime is linked for extensions
ifneq (,$(findstring --omp,$(OMPFLAGS)))
  # Platform-specific OpenMP library handling
  UNAME_S := $(shell uname -s)
  
  ifeq ($(UNAME_S),Darwin)
    # macOS: Use libomp to avoid emutls conflicts
    # Check Homebrew locations (Apple Silicon first, then Intel)
    LIBOMP_PREFIX := $(shell [ -d /opt/homebrew/opt/libomp ] && echo /opt/homebrew/opt/libomp || echo /usr/local/opt/libomp)
    
    ifneq ($(wildcard $(LIBOMP_PREFIX)/lib/libomp.dylib),)
      # libomp found - use it
      OMP_LDFLAGS = -L$(LIBOMP_PREFIX)/lib -lomp -Wl,-rpath,$(LIBOMP_PREFIX)/lib
      $(info Using libomp from $(LIBOMP_PREFIX))
    else
      # Fallback: try to find libgomp (will likely cause TLS issues)
      LIBGOMP      := $(shell gfortran -print-file-name=libgomp.dylib 2>/dev/null)
      LIBGOMP_DIR  := $(dir $(LIBGOMP))
      OMP_LDFLAGS   = -L$(LIBGOMP_DIR) -lgomp -Wl,-rpath,$(LIBGOMP_DIR)
      $(warning libomp not found at $(LIBOMP_PREFIX) - falling back to libgomp (may cause TLS issues))
      $(warning Install with: brew install libomp)
    endif
  else
    # Linux/other: Use libgomp
    LIBGOMP      := $(shell gfortran -print-file-name=libgomp.so)
    LIBGOMP_DIR  := $(dir $(LIBGOMP))
    OMP_LDFLAGS   = -L$(LIBGOMP_DIR) -lgomp -Wl,-rpath,$(LIBGOMP_DIR)
  endif
endif

ifneq (,$(findstring --omp,$(OMPFLAGS)))
  FORTHON_ENV = LDFLAGS="$(LDFLAGS) $(OMP_LDFLAGS)"
else
  FORTHON_ENV =
endif


LINKMAPDIR ?= $(BUILDDIR)/linkmaps

all:    $(BUILDDIR)/compydep.$(PYTAG) \
        $(BUILDDIR)/bbbpydep.$(PYTAG) \
        $(BUILDDIR)/aphpydep.$(PYTAG) \
        $(BUILDDIR)/apipydep.$(PYTAG) \
        $(BUILDDIR)/ppppydep.$(PYTAG) \
        $(BUILDDIR)/flxpydep.$(PYTAG) \
        $(BUILDDIR)/grdpydep.$(PYTAG) \
        $(BUILDDIR)/svrpydep.$(PYTAG) \
        $(BUILDDIR)/wdfpydep.$(PYTAG) \
        $(BUILDDIR)/nclpydep.$(PYTAG)
	rm -f uedgeC.so

$(BUILDDIR)/compydep.$(PYTAG): \
            com/blasext.F \
            com/brent.F \
            com/comutil.F \
            com/misc.F \
            com/mnbrak.F \
            com/dsum.f \
            com/dummy_py.f \
            com/error.f \
            com/getmsg.f \
            com/ssum.f \
            com/$(PETSC-COM) \
            com/com.v
	$(FORTHON_ENV) $(FORTHON) \
            -a $(INSTALLARGS) \
            -a $(FCOMP) $(DEBUG) \
            --interfacefile com/com.v \
            -f  com/blasext.F \
                com \
                com/brent.F \
                com/comutil.F \
                com/misc.F com/mnbrak.F \
                com/dsum.f \
                com/dummy_py.f \
                com/error.f \
                com/getmsg.f \
                com/ssum.f \
                $(PETSC-COM)
	touch $@

$(BUILDDIR)/aphpydep.$(PYTAG): \
            $(BUILDDIR)/compydep.$(PYTAG) \
            aph/aphrates.F \
            aph/aphread.F \
            aph/aph.v
	$(FORTHON) \
        -a $(INSTALLARGS)  \
        -a $(FCOMP) $(DEBUG) \
        --interfacefile aph/aph.v \
        -f  aph/aphrates.F \
            aph \
            aph/aphread.F
	touch $@

$(BUILDDIR)/apipydep.$(PYTAG): \
            $(BUILDDIR)/compydep.$(PYTAG) \
            api/apifcn.F \
            api/apip93.F \
            api/apisorc.F \
            api/fimp.F \
            api/fmombal.F \
            api/inelrates.F \
            api/sputt.F api/api.v \
            com/com.v
	$(FORTHON_ENV) $(FORTHON) \
        -a $(INSTALLARGS)  \
        -a $(FCOMP) $(DEBUG) \
        --interfacefile api/api.v \
        -d com \
        -f  api/apifcn.F \
            api \
            api/apip93.F \
            api/apisorc.F \
            api/fimp.F \
            api/fmombal.F \
            api/inelrates.F \
            api/sputt.F
	touch $@

$(BUILDDIR)/bbbpydep.$(PYTAG): \
            $(BUILDDIR)/compydep.$(PYTAG) \
            bbb/pandf_boundary.F \
            bbb/convert.F \
            bbb/geometry.F \
            bbb/griddubl.F \
            bbb/oderhs.F \
            bbb/pandf.F \
            bbb/pandf_gas_energy.F	\
            bbb/pandf_jacobian.F \
            bbb/pandf_plasma_continuity.F \
            bbb/pandf_gas_continuity.F \
            bbb/pandf_plasma_momentum.F \
            bbb/pandf_plasma_energy.F \
            bbb/odesetup.F \
            bbb/odesolve.F \
            bbb/pandf_potencur.F \
            bbb/turbulence.F \
            bbb/ext_neutrals.F \
            bbb/bbb.v \
            com/com.v
	$(FORTHON_ENV) $(FORTHON) \
        -a $(INSTALLARGS)  \
        -a $(FCOMP) $(DEBUG) \
        --interfacefile bbb/bbb.v \
        --macros    com/com.v \
                    $(READLINE) \
        -d com \
        -f  bbb/pandf_boundary.F \
            bbb \
            bbb/convert.F \
            bbb/geometry.F \
            bbb/griddubl.F \
            bbb/pandf.F \
            bbb/pandf_gas_energy.F	\
            bbb/pandf_jacobian.F \
            bbb/pandf_plasma_continuity.F \
            bbb/pandf_gas_continuity.F \
            bbb/pandf_plasma_momentum.F \
            bbb/pandf_plasma_energy.F \
            bbb/oderhs.F \
            bbb/odesetup.F \
            bbb/odesolve.F \
            bbb/pandf_potencur.F \
            bbb/turbulence.F \
            bbb/ext_neutrals.F
	touch $@

$(BUILDDIR)/ppppydep.$(PYTAG): \
            $(BUILDDIR)/compydep.$(PYTAG) \
            $(BUILDDIR)/bbbpydep.$(PYTAG) \
            ppp/parallel.F90 \
            ppp/omp_parallel.F90 \
            ppp/debug_parallel.F90 \
            ppp/ppp.v \
            com/com.v \
            bbb/bbb.v
	@echo "Building ppppy (OMP_LDFLAGS='$(OMP_LDFLAGS)')"
	$(FORTHON_ENV) $(FORTHON) \
        -a $(INSTALLARGS) -a $(FCOMP) $(DEBUG) \
	    --interfacefile ppp/ppp.v \
        --macros com/com.v \
        --macros bbb/bbb.v \
        -d com \
        -d bbb \
	    -f  ppp/parallel.F90 \
            ppp \
            ppp/omp_parallel.F90 \
            ppp/debug_parallel.F90
	touch $@


$(BUILDDIR)/flxpydep.$(PYTAG): \
            $(BUILDDIR)/compydep.$(PYTAG) \
            flx/flxcomp.F \
            flx/flxdriv.F \
            flx/flxread.F \
            flx/flxwrit.F \
            flx/flx.v \
            com/com.v
	$(FORTHON_ENV) $(FORTHON) \
            -a $(INSTALLARGS)  \
            -a $(FCOMP) $(DEBUG) \
            --interfacefile flx/flx.v \
            -d com \
            -f  flx/flxcomp.F \
                flx \
                flx/flxdriv.F \
                flx/flxread.F \
                flx/flxwrit.F
	touch $@

$(BUILDDIR)/grdpydep.$(PYTAG): \
            $(BUILDDIR)/compydep.$(PYTAG) \
            grd/grdcomp.F \
            grd/grddriv.F \
            grd/grdinit.F \
            grd/grdread.F \
            grd/grdwrit.F \
            grd/grd.v \
            com/com.v
	$(FORTHON_ENV) $(FORTHON) \
            -a $(INSTALLARGS)  \
            -a $(FCOMP) $(DEBUG) \
            --interfacefile grd/grd.v \
            -d com \
            -f  grd/grdcomp.F \
                grd \
                grd/grddriv.F \
                grd/grdinit.F \
                grd/grdread.F \
                grd/grdwrit.F
	touch $@



$(BUILDDIR)/svrpydep.$(PYTAG): \
            $(BUILDDIR)/bbbpydep.$(PYTAG) \
            svr/daspk.F \
            svr/nksol.F \
            svr/svrut1.F \
            svr/svrut2.F \
            svr/svrut3.F \
            svr/svrut4.F \
            svr/vodpk.F \
            svr/uoa.F \
            svr/daux1.f \
            svr/$(PETSC-UEDGE) \
            svr/svr.v
	$(FORTHON_ENV) $(FORTHON) \
            -a $(INSTALLARGS)  \
            -a $(FCOMP) $(DEBUG) \
            --interfacefile svr/svr.v \
            --macros bbb/bbb.v \
            -d bbb \
            -f  svr/daspk.F \
                svr \
                svr/nksol.F \
                svr/svrut1.F \
                svr/svrut2.F \
                svr/svrut3.F \
                svr/svrut4.F \
                svr/vodpk.F \
                svr/uoa.F \
                svr/daux1.f \
                $(PETSC-UEDGE)
	touch $@

$(BUILDDIR)/wdfpydep.$(PYTAG): \
            wdf/wdf.F \
            wdf/wdf.v
	$(FORTHON_ENV) $(FORTHON) \
            -a $(INSTALLARGS)  \
            -a $(FCOMP) $(DEBUG) \
            --interfacefile wdf/wdf.v \
            -f  wdf/wdf.F \
                wdf
	touch $@

$(BUILDDIR)/nclpydep.$(PYTAG): \
            ncl/ncl_driver.m \
            ncl/ncl.v \
            ncl/nclass_mod.f \
            ncl/rarray_copy.f \
            ncl/rarray_sum.f \
            ncl/rarray_zero.f  \
            ncl/u_erf.f \
            ncl/u_lu_backsub.f \
            ncl/u_lu_decomp.f \
            ncl/write_mod.f
	$(FORTHON_ENV) $(FORTHON) \
            -a $(INSTALLARGS)  \
            -a $(FCOMP) $(DEBUG) \
            --interfacefile ncl/ncl.v \
            -f  ncl/ncl_driver.F \
                ncl \
                ncl/nclass_mod.f \
                ncl/rarray_copy.f \
                ncl/rarray_sum.f \
                ncl/rarray_zero.f  \
                ncl/u_erf.f \
                ncl/u_lu_backsub.f \
                ncl/u_lu_decomp.f \
                ncl/write_mod.f





public: all
	publishpyuedge90.py $(PUBLICHOME)

update:
	for dir in $(PUBLICHOME); do \
	  cd $$dir; \
	  cvs update; \
	done

clean:
	@echo $(NOCLEAN)
ifeq ($(NOCLEAN),FALSE)
	@echo Starting cleaning of build directory
	find . -depth -name build ! -ipath '*site-packages*' -exec rm -rf {} \;
	find . -depth -name __pycache__ -exec rm -rf {} \;
	find . -name \*.pyc -exec rm {} \;
	find . -name \*.F -exec rm {} \;
	touch uedgeC_Forthon.c
else
	@echo No clean of build requested: proceeding

endif 

#----------------------------------------------------------------------------
#--- Build command for opendx wrapper.
DX: pyDXObject.c
	$(MYPYTHON) DXsetup.py build --build-platlib .

#----------------------------------------------------------------------------




# ensure linkmap dir exists
$(LINKMAPDIR):
	@mkdir -p $@

# Add link maps for the modules most implicated in TLS descriptor collisions
# (you can extend this list later)
$(BUILDDIR)/ppppydep.$(PYTAG): | $(LINKMAPDIR)
$(BUILDDIR)/ppppydep.$(PYTAG): LDFLAGS += -Wl,-map,$(LINKMAPDIR)/ppppy.$(PYTAG).map

$(BUILDDIR)/bbbpydep.$(PYTAG): | $(LINKMAPDIR)
$(BUILDDIR)/bbbpydep.$(PYTAG): LDFLAGS += -Wl,-map,$(LINKMAPDIR)/bbbpy.$(PYTAG).map

$(BUILDDIR)/apipydep.$(PYTAG): | $(LINKMAPDIR)
$(BUILDDIR)/apipydep.$(PYTAG): LDFLAGS += -Wl,-map,$(LINKMAPDIR)/apipy.$(PYTAG).map

# --- TLS audit: call external script that is wheel-aware ----
TOOLS_DIR := $(CURDIR)/buildscripts
TLS_AUDIT := $(TOOLS_DIR)/tls_audit.sh
BUILD_LIB_DIR := build

.PHONY: tls-audit
tls-audit:
	@mkdir -p $(BUILD_LIB_DIR)/linkmaps
	@echo "Running TLS audit script..."
	@if [ -x "$(TLS_AUDIT)" ]; then \
	  $(TLS_AUDIT) "$(BUILD_LIB_DIR)" "uedge" "--fail-on-dup" || true; \
	else \
	  echo "WARNING: $(TLS_AUDIT) not found or not executable; skipping TLS audit."; \
	fi

