#PETSC_DIR   = /homes/mccomic/petsc-uedge
#PETSC_ARCH  = linux-uedge
FARGS       = --fargs  -I$(PETSC_DIR) --fargs -I$(PETSC_DIR)/$(PETSC_ARCH)/include \
              --fargs -I$(PETSC_DIR)/include -I$(PETSC_DIR)/include/mpiuni --fargs -DUSE_PETSC 
#FCOMP       = -F g95 $(FARGS)
FCOMP       = $(FARGS)

include Makefile.Forthon3

MYPYTHONP = python-uedge
SETUPOPTS   = --petsc
PETSC-UEDGE = petsc-uedge.F90
PETSC-COM = petscMod.F90

