# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install forthon mppl numpy h5py
        python -m pip install flake8
        python -m pip install pytest-forked pytest-xdist
    - name: Build UEDGE
      run: |
        python setup.py build
        python setup.py install
    - name: Checkout pytest branch
      uses: actions/checkout@v4
      with:
        ref: pytests
    - name: Test with pytest from dedicated branch
      run: |
        # Create a clean UEDGE instance for every test
        pytest --forked --tb=native pytests/pytests
